[package]
name = "lotto_registration_manager_contract"
version = "2.0.0"
authors = ["guigou"]
edition = "2021"

[dependencies]
ink = { version = "5.1.1", default-features = false }
ink_client_lib = { git = "https://github.com/GuiGou12358/sc-rollup", default-features = false}
lotto = { path = "../../logic", default-features = false }

[dev-dependencies]
hex = "0.4.3"

[lib]
path = "lib.rs"

[features]
default = ["std"]
std = [
    "ink/std",
    "ink_client_lib/std",
    "lotto/std",
]
ink-as-dependency = []

[profile.release]
overflow-checks = false

[profile.dev]
overflow-checks = false
