[package]
name = "e2e_tests"
version = "0.1.1"
authors = ["guigou"]
edition = "2021"

[dependencies]
ink = { version = "5.1.1", default-features = false }
ink_client_lib = { git = "https://github.com/GuiGou12358/sc-rollup", default-features = false}
lotto = { path = "../logic", default-features = false }
lotto_registration_manager_contract = { path = "../contracts/raffle_manager", default-features = false, features = ["ink-as-dependency"] }
lotto_registration_contract = { path = "../contracts/raffle_registration", default-features = false, features = ["ink-as-dependency"] }

[dev-dependencies]
ink_e2e = { version = "5.1.1" }
hex-literal = { version = "1.0.0" }
hex = "0.4.3"
subxt-signer = { version = "0.42.1" }

[lib]
path = "lib.rs"

[features]
default = ["std"]
std = [
    "ink/std",
    "ink_client_lib/std",
    "lotto/std",
    "lotto_registration_manager_contract/std",
    "lotto_registration_contract/std",
]
ink-as-dependency = []
e2e-tests = []

[profile.release]
overflow-checks = false

[profile.dev]
overflow-checks = false
